server:
  port: 8083
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: tg-chats-collector
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: tg_chats_collector
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema};
  liquibase:
    enabled: true
    change-log: ./db/changelog/changelog-master.yml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

tg-collector:
  telegram:
    client:
      api-id: ${TG_CLIENT_API_ID}
      api-hash: ${TG_CLIENT_API_HASH}
      phone: ${TG_CLIENT_PHONE}
    bot:
      token: ${TG_BOT_TOKEN}
      sk-reading-chat-id: ${SK_READING_CHAT_ID}
      sk-publishing-chat-id: ${SK_PUBLISHING_CHAT_ID}
  chat-loader:
    default-messages-limit: 2000
    default-days-before-limit: 60
  integration:
    conveyor:
      host: ${INTEGRATION_CONVEYOR_HOST}

logging:
  log-exec-time: true
  web-logging:
    log-body: true
    log-feign-requests: true