version: '3.3'

services:
  tg-chats-collector:
    image: ghcr.io/panyukovnn/tg-chats-collector:${APP_TAG}
    container_name: tg-chats-collector
    environment:
      SPRING_PROFILES_ACTIVE: prom
    ports:
      - "127.0.0.1:8083:8083"
      - "172.17.0.1:8083:8083"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - /etc/common-config/config.env
    volumes:
      - ./tdlight-session:/tdlight-session
      - ./application-prom.yaml:/application-prom.yaml