version: '3.3'

services:
  tg-chats-collector:
    image: ghcr.io/panyukovnn/tg-chats-collector:${APP_TAG}
    container_name: tg-chats-collector
    environment:
      SPRING_PROFILES_ACTIVE: prom
    ports:
      - 8083:8083
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./config.env
      - /etc/common-config/config.env
    volumes:
      - ./tdlight-session:/tdlight-session